# Generated by Django 6.0.3 on 2026-03-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer_workflow', '0002_add_constraints'),
        ('reviewer_workflow', '0003_reviewertask_indexes'),
    ]

    operations = [
    ]
