# Generated by Django 6.0.3 on 2026-03-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_display_name_suspended_status'),
        ('users', '0004_user_display_name'),
    ]

    operations = [
    ]
