# Generated by Django 6.0.3 on 2026-03-10 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_text', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prompt_templates',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('execution_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('clarify', 'Clarification Requested')], default='pending', max_length=50)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('used_llm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chat_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='chat_logs_user_id_50cffa_idx'), models.Index(fields=['session_id'], name='chat_logs_session_35922e_idx'), models.Index(fields=['intent'], name='chat_logs_intent_91efc1_idx'), models.Index(fields=['created_at'], name='chat_logs_created_00b4c5_idx')],
            },
        ),
    ]
