# Generated by Django 6.0.3 on 2026-03-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_assistant', '0004_chatlog_update_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='execution_status',
            field=models.CharField(choices=[('needs_input', 'Needs Input (Slot-Fill)'), ('awaiting_confirm', 'Awaiting Confirmation'), ('success', 'Success'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('clarify', 'Clarification Requested'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
